let db = db.getSiblingDB('customerDb');

db.customers.insertMany([
  {
    cpf: '04045709096',
    name: 'John Doe',
    email: 'john.doe@gmail.com',
    phone: '(11) 98456-7985',
    address: {
      street: 'Praça da Sé',
      number: NumberInt(100),
      neighborhood: 'Centro',
      state: 'São Paulo',
      city: 'São Paulo',
      zipcode: '00000-001',
      complement: '',
    },
    createAt: new Date(),
  },
  {
    cpf: '13082239510',
    name: 'Sabrina Clarice Tânia Cavalcanti',
    email: 'sabrina-cavalcanti90@msaengenharia.com.br',
    phone: '(65) 98304-1176',
    address: {
      street: 'Avenida Principal',
      number: NumberInt(699),
      neighborhood: 'Centro',
      state: 'Boa Esperança',
      city: 'Mato Grosso',
      zipcode: '78896-972',
      complement: '',
    },
    createAt: new Date(),
  },
  {
    cpf: '47215392740',
    name: 'Leonardo Cláudio Nogueira',
    email: 'leonardo.claudio.nogueira@robiel.com.br',
    phone: '(83) 99155-5313',
    address: {
      street: 'Rua Etiene Travassos',
      number: NumberInt(255),
      neighborhood: 'Padre Zé',
      state: 'João Pessoa',
      city: 'Paraíba',
      zipcode: '58026-043',
      complement: '',
    },
    createAt: new Date(),
  },
  {
    cpf: '63397048834',
    name: 'Pietro Eduardo Gonçalves',
    email: 'pietro.eduardo.goncalves@zizafernandes.com',
    phone: '(11) 99979-2537',
    address: {
      street: 'Rua Hugo Pierson',
      number: NumberInt(255),
      neighborhood: 'Cidade Ipava',
      state: 'São Paulo',
      city: 'São Paulo',
      zipcode: '04950-006',
      complement: '',
    },
    createAt: new Date(),
  },
  {
    cpf: '10312988869',
    name: 'Sebastiana Lara da Rochas',
    email: 'sebastiana-darocha91@power.alstom.com',
    phone: '(11) 99694-1939',
    address: {
      street: 'Avenida Miguel de Castro',
      number: NumberInt(665),
      neighborhood: 'Vila Pereira Barreto',
      state: 'São Paulo',
      city: 'São Paulo',
      zipcode: '02950-000',
      complement: '',
    },
    createAt: new Date(),
  },
  {
    cpf: '10830539816',
    name: 'Renato Lucca Bruno Fernandes',
    email: 'renato-fernandes79@paraisopolis.com.br',
    phone: '(11) 98362-2145',
    address: {
      street: 'Rua Copará',
      number: NumberInt(157),
      neighborhood: 'Vila Santo Henrique',
      state: 'São Paulo',
      city: 'São Paulo',
      zipcode: '03707-050',
      complement: '',
    },
    createAt: new Date(),
  },
  {
    cpf: '01266400923',
    name: 'Paulo Caleb Henry Cauê Mendes',
    email: 'caleb.henry.mendes@igoralcantara.com.br',
    phone: '(48) 98526-6049',
    address: {
      street: 'Rua Ivo Silveira 36',
      number: NumberInt(254),
      neighborhood: 'Centro',
      state: 'Santa Catarina',
      city: 'Anitápolis',
      zipcode: '88475-970',
      complement: '',
    },
    createAt: new Date(),
  },
]);
