POST http://localhost:3000/ HTTP/1.1
content-type: application/json

{
  "cpf": "048.898.780-68",
  "name": "John Doe",
  "email": "joe.doe13@gmail.com",
  "phone": "(11) 98456-7985",
  "address": {
    "street": "Praça da Sé",
    "number": 100,
    "neighborhood": "Centro",
    "state": "São Paulo",
    "city": "São Paulo",
    "zipcode": "00000-001",
    "complement": ""
  }
}